### PR TITLE
.travis.yml: move Travis to Go1.11

### PR DESCRIPTION
**Pull request by pjanotti**
We are using go.mod files to manage the packages consumed by the project,
so we need to move to go 1.11 where the feature is actually available.

### CODE REVIEW

**Comment by odeke-em** [comment]
Houston we have a go ahead now for this PR, all the blocking PRs have been merged, all yours @pjanotti to rebase then we can merge!

**Comment by pjanotti** [comment]
travis failure is data race https://travis-ci.org/census-instrumentation/opencensus-service/builds/452159703#L871

**Comment by pjanotti** [comment]
The test failure above is not related this PR. I am going to merge it and open a separate issue for the test failure.

**Comment by odeke-em** [comment]
@pjanotti that race is from https://github.com/census-instrumentation/opencensus-service/pull/156
which should have stayed as a concurrent buffer to protect from concurrent writes and reads, I'll send a PR reverting that part.

**Pull request merged**
