### PR TITLE
Upgrade Stackdriver exporter version.

### PR DESCRIPTION
**Pull request by songy23**
See https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/164 and https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/165.

### CODE REVIEW

**Comment by songy23** [comment]
@flands @sjkaris can either of you help us make a patch release with the recent fixes (we're also waiting on https://github.com/census-instrumentation/opencensus-service/pull/587)?

**Comment by sjkaris** [comment]
@songy23 I will make a patch release later today. Are there any other pending changes that we should get in before cutting it?

**Comment by songy23** [comment]
Thanks! I think that's all we have - @rghetia do you have any other pending changes?

**Comment by rghetia** [comment]
no. I don’t have anything pending.

**Comment by sjkaris** [comment]
@songy23 @rghetia I released version 0.1.8.2 !

**Comment by songy23** [comment]
Great, thanks!

**Pull request merged**
