### PR TITLE
Upgrade opencensus-proto version to v0.2.0.

### PR DESCRIPTION
**Pull request by songy23**

### CODE REVIEW

**Comment by songy23** [comment]
> If you run GO111MODULE=on go mod tidy it should also remove the old opencensus-proto v0.1.* entry in go.sum

Looks like it removed something else. Could it be due to other indirect dependency on v0.1.0 proto?

**Comment by odeke-em** [comment]
> Looks like it removed something else. Could it be due to other indirect dependency on v0.1.0 proto?

I think it is because of the Prometheus metrics exporter and receiver that were pinned to v0.1.0*

**Comment by odeke-em** [comment]
I've pushed up https://github.com/orijtech/promreceiver/commit/69e7d86249bf6840367b4149ee5ec5c633eb0b0a and now going to do the same for the prometheus-metrics-exporter. Once those no longer take that proto dependency, we'll be clear. Obviously this is temporary and will change once they are merged in here when https://github.com/census-instrumentation/opencensus-service/pull/479 and https://github.com/census-instrumentation/opencensus-service/pull/481 are merged!

**Comment by odeke-em** [comment]
@songy23 now if you just do `GO111MODULE=on go get github.com/orijtech/promreceiver@v0.4.0` and then finally `GO111MODULE=on go mod tidy` all should now be cleared as promreceiver is now bumped up to use OpenCensus-Proto v0.2.0

**Comment by odeke-em** [comment]
Also there is a legit failure from the opencensus-proto/gen-go files
```shell
# github.com/census-instrumentation/opencensus-proto/gen-go/agent/common/v1
../../../../pkg/mod/github.com/census-instrumentation/opencensus-proto@v0.2.0/gen-go/agent/common/v1/common.pb.go:22:11: undefined: proto.ProtoPackageIsVersion3
# github.com/census-instrumentation/opencensus-proto/gen-go/resource/v1
../../../../pkg/mod/github.com/census-instrumentation/opencensus-proto@v0.2.0/gen-go/resource/v1/resource.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3
```

**Comment by songy23** [comment]
v0.4.0 not found:
```bash
$ GO111MODULE=on go get github.com/orijtech/promreceiver@v0.4.0
go: finding github.com/orijtech/promreceiver v0.4.0
go get github.com/orijtech/promreceiver@v0.4.0: unknown revision v0.4.0
```

> Also there is a legit failure from the opencensus-proto/gen-go files

Looking

**Comment by odeke-em** [comment]
Hmm, that's odd as I published it 1+ hour ago https://github.com/orijtech/promreceiver/releases/tag/v0.0.4 but perhaps you might need to add `-u` to update your version but really `go mod` should do it for you.

**Comment by odeke-em** [comment]
@songy23 I just noticed, we'll also need to update the ocagent-exporters-{ocagent, stackdriver}
I've mailed so far: https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/48

**Comment by songy23** [comment]
> Also there is a legit failure from the opencensus-proto/gen-go files

Seems to be the same issue to https://github.com/golang/protobuf/issues/763.

**Comment by songy23** [comment]
> Also there is a legit failure from the opencensus-proto/gen-go files

https://github.com/census-instrumentation/opencensus-service/pull/490/commits/3391b6c689a0cd6adebd3c5476df9b0e48ca1842 resolved this. Now we need to update OC-Go Stackdriver exporter (https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/102) and OC-Agent exporter (https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/48) to use the new oc-proto release.

**Comment by songy23** [comment]
> if you just do GO111MODULE=on go get github.com/orijtech/promreceiver@v0.4.0
> Hmm, that's odd as I published it 1+ hour ago https://github.com/orijtech/promreceiver/releases/tag/v0.0.4 but perhaps you might need to add -u to update your version but really go mod should do it for you.

Updated. This should be 0.0.4 instead of 0.4.0.

**Comment by pjanotti** [comment]
It still has issues on Travis https://travis-ci.org/census-instrumentation/opencensus-service/builds/505609648#L1012-L1018

```
# github.com/orijtech/prometheus-go-metrics-exporter
../../../../pkg/mod/github.com/orijtech/prometheus-go-metrics-exporter@v0.0.2/prometheus.go:131:17: metric.GetName undefined (type *"github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric has no field or method GetName)
# github.com/orijtech/promreceiver
../../../../pkg/mod/github.com/orijtech/promreceiver@v0.0.4/buffering.go:144:3: unknown field 'Descriptor_' in struct literal of type "github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric
# github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics [github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics.test]
receiver/opencensusreceiver/ocmetrics/opencensus_test.go:436:3: unknown field 'Descriptor_' in struct literal of type "github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric
```

**Comment by odeke-em** [comment]
Roger that @pjanotti! @songy23 if you update with `GO111MODULE=on go get github.com/orijtech/promreceiver@v0.0.5` it should be good to go now. I had to also go adjust to the breaking OpenCensus-Proto changes but now should be all golden.

**Comment by songy23** [comment]
@odeke-em @pjanotti @bogdandrutu All build failures and most test failures are fixed. CI is green now. Follow-up items are tracked in https://github.com/census-instrumentation/opencensus-service/issues/492. Thanks for the review and help!

**Pull request merged**
