### PR TITLE
translator/trace: OCSpanDataToProtoSpan

### PR DESCRIPTION
**Pull request by odeke-em**
Provides a function to translate OpenCensus SpanData
into *tracepb.Span, with tests. It is the first half of
the trace converters task.

Updates #26

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Not sure we need this here (cannot see for the moment when we will use this). Also do we not need this functionality in the ocagent-exporter?

**Comment by songy23** [comment]
> Not sure we need this here (cannot see for the moment when we will use this). Also do we not need this functionality in the ocagent-exporter?

Agree, AFAIS this should be a functionality for Agent exporters.

**Comment by odeke-em** [comment]
@bogdandrutu @songy23 currently we don't need it but I implemented it as it is an item on our task list. Yes this functionality is used in the Go-exporter but I was wondering if perhaps we should have it in one place and import from a set of common libraries.

**Comment by odeke-em** [comment]
This PR was an overzealous interpretation of the tasks. We already have this functionality in the agent-exporters. I'll close it for now but the functionality is trivial to retrieve if we ever need it.

Thanks y'all for the reviews!

**Pull request closed without merging**
