### PR TITLE
Add support for codecov.

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
It will show you that.

**Comment by bogdandrutu** [comment]
https://codecov.io/gh/census-instrumentation/opencensus-service/tree/2599c57a7bcc6f7eaaee85e692be5cd7e264ef59

**Comment by sjkaris** [comment]
If possible, adding https://docs.codecov.io/docs/pull-request-comments would be great also, so that the coverage changes are highly visible on each PR. (not sure if you already did this or planned to)

**Comment by bogdandrutu** [comment]
@sjkaris that is automatically enabled, but I think it does not work if you have a failing check (like we have the appveyor).

**Pull request merged**
