### PR TITLE
agent: Trace+Config services implemented

### LINKED ISSUE #18: all: a bare bones agent that implements agent{Trace, Config} services
Over the past couple of weeks we've been working on the agent service. To get things started we need to implement an agent that conforms to this proto https://github.com/census-instrumentation/opencensus-proto/tree/master/src/opencensus/proto/agent and as a gRPC service.

We've also implemented a Go exporter that already conforms to it https://github.com/census-ecosystem/opencensus-go-exporter-ocagent

### PR DESCRIPTION
**Pull request by odeke-em**
* all: rewrite from groundup
Due to the complexity of setting up repositories, it has
been advised that we reuse this repository. However, since
the agent spec has radically changed and is being
implemented from the ground up, we are rewriting this
code hence the deletions.

* Trace & Config services implemented along with
hooks that will be used by the frontend/consumer
of the agent itself. Please see the tests for
how these hooks are used or just read the godoc
for the various `AgentOption`s.

* .travis.yml: upgrade to Go1.11

Fixes #18

### CODE REVIEW

**Comment by odeke-em** [comment]
Travis CI is failing due to https://github.com/census-instrumentation/opencensus-service/issues/22 /cc @bogdandrutu

**Comment by odeke-em** [comment]
@songy23 sure, the code deletion PR is https://github.com/census-instrumentation/opencensus-service/pull/28 PTAL.

**Comment by bogdandrutu** [comment]
I cannot review a PR that does 900+ deletions and also adds new code. Please initially delete the old code if you need that then add new code.

**Comment by odeke-em** [comment]
>I cannot review a PR that does 900+ deletions and also adds new code. Please initially delete the old code if you need that then add new code.

@bogdandrutu sure, done in https://github.com/census-instrumentation/opencensus-service/pull/25#issuecomment-423290362 PR https://github.com/census-instrumentation/opencensus-service/pull/28

**Comment by odeke-em** [comment]
No longer necessary. Broken out by #40 #34 #36.

**Pull request closed without merging**
