### PR TITLE
all: rewrite from groundup

### PR DESCRIPTION
**Pull request by odeke-em**
Due to the complexity of setting up repositories, it has
been advised that we reuse this repository. However, since
the agent spec has radically changed and is being
implemented from the ground up, we are rewriting this
code hence the deletions.

### CODE REVIEW

**Comment by odeke-em** [comment]
Thanks for the review @songy23! I think this change is going to be stalled as @rakyll needs this repo as is for some demos, as per offline email communication -- unless am mistaken.

**Comment by songy23** [comment]
Make sense to me. Let's hold off this PR for now, meanwhile we can still do the implementation in other PRs.

**Comment by bogdandrutu** [comment]
For the moment to not break the old prototype consider to move it into a directory "/old" or something like that.

**Comment by odeke-em** [comment]
No longer necessary. Replaced by the proper code placements #34 #35 #36.

**Pull request closed without merging**
